# Mapping of timezones to country codes for supported timezones only
# This is a partial mapping and can be extended as needed
TIMEZONE_COUNTRY_MAP = {
    # Americas
    "EST": ["US", "CA", "BS", "KY", "JM"],
    "PST": ["US", "CA", "MX"],
    "CST": ["US", "CA", "MX", "GT", "SV", "HN", "NI", "CR"],
    "MST": ["US", "CA", "MX"],
    "AST": ["CA", "AG", "AI", "AW", "BB", "BL", "BQ", "CW", "DM", "GD", "GP", "KN", "LC", "MF", "MQ", "MS", "PR", "SX", "TT", "VC", "VG", "VI"],
    "AKST": ["US"],
    "HST": ["US"],
    "BRT": ["BR"],
    "ART": ["AR"],
    "CLT": ["CL"],
    "PET": ["PE"],
    "COT": ["CO"],
    "VET": ["VE"],
    "UYT": ["UY"],
    "PYT": ["PY"],
    # Europe
    "CET": ["FR", "DE", "IT", "ES", "PL", "BE", "NL", "CH", "AT", "DK", "NO", "SE", "CZ", "HU", "SK", "SI", "HR", "BA", "ME", "RS", "MK", "AL", "LU"],
    "GMT": ["GB", "IE", "PT", "IS", "GH", "GM", "GN", "SL", "LR", "CI", "BF", "TG"],
    "EET": ["FI", "EE", "LT", "LV", "UA", "RO", "BG", "GR", "CY", "SY", "EG", "TR"],
    "WET": ["PT", "ES", "MA"],
    "MSK": ["RU", "BY"],
    "BST": ["GB"],
    "CEST": ["FR", "DE", "IT", "ES", "PL", "BE", "NL", "CH", "AT", "DK", "NO", "SE", "CZ", "HU", "SK", "SI", "HR", "BA", "ME", "RS", "MK", "AL", "LU"],
    "TRT": ["TR"],
    # Asia
    "IST": ["IN"],
    "JST": ["JP"],
    "KST": ["KR"],
    "CST": ["CN", "TW", "MY", "SG"],
    "SGT": ["SG"],
    "HKT": ["HK"],
    "GST": ["AE"],
    "IRST": ["IR"],
    "PKT": ["PK"],
    "BST": ["BD"],
    "NPT": ["NP"],
    "MMT": ["MM"],
    "ICT": ["TH", "KH", "LA", "VN"],
    "PHT": ["PH"],
    "WIT": ["ID"],
    "CIT": ["ID"],
    "EIT": ["ID"],
    "TST": ["TW"],
    "MST": ["MY"],
    # Oceania
    "AEST": ["AU"],
    "ACST": ["AU"],
    "AWST": ["AU"],
    "NZST": ["NZ"],
    "NZDT": ["NZ"],
    "FJT": ["FJ"],
    "PGT": ["PG"],
    # Africa
    "SAST": ["ZA"],
    "EAT": ["KE", "TZ", "UG", "ET", "DJ", "ER", "SO", "KM"],
    "WAT": ["NG", "AO", "BJ", "CD", "CF", "CG", "GA", "GQ"],
    "CAT": ["BW", "BI", "MW", "MZ", "RW", "ZM", "ZW"],
    "EET": ["EG", "LY"],
    "MUT": ["MU"],
    "SCT": ["SC"],
    "MVT": ["MV"],
    # Pacific
    "SST": ["WS"],
    "TOT": ["TO"],
    "CHUT": ["FM"],
    "PONT": ["PW"],
    # Russia
    "YEKT": ["RU"],
    "OMST": ["RU"],
    "KRAT": ["RU"],
    "IRKT": ["RU"],
    "YAKT": ["RU"],
    "VLAT": ["RU"],
    "MAGT": ["RU"],
    "PETT": ["RU"],
    # Middle East
    "AST": ["SA", "QA", "BH", "KW", "IQ", "JO", "LB", "PS", "SY", "YE"],
    "TRT": ["TR"],
    "AFT": ["AF"],
    # Central Asia
    "UZT": ["UZ"],
    "TJT": ["TJ"],
    "TMT": ["TM"],
    "KGT": ["KG"],
    "ALMT": ["KZ"]
}
